[client]
showSidebarNavigation = false

[server]
enableCORS = false
enableXsrfProtection = false

[browser]
gatherUsageStats = false

[theme]
base = "light"
primaryColor = "#164EC6"
backgroundColor = "#FAFBFC"
secondaryBackgroundColor = "#FFFFFF"
textColor = "#111827"
font = "sans serif"